dev_addresses:
  admin: https://demo-sso.digikala.com/dev/cli/
  fulfillment: https://demo-fc.digikala.com/dev/cli/
admin_command:
  create_user: supernova:digikala:account:admin:create
  number_of_users: supernova:digikala:account:number:picker:test
arguments:
  create_user: email, pass, phone
  number_of_users: prefix, number